// <auto-generated />
namespace casino_oxana_back.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mg142 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mg142));
        
        string IMigrationMetadata.Id
        {
            get { return "202003101614045_mg142"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
